import { Navbar } from "@/components/features/navbar"
import { Footer } from "@/components/features/footer"
import { AfricanAgentAvatar } from "@/components/ui/african-agent-avatar"
import { Shield, Zap, Brain, Code, MessageSquare, Search, Palette, BarChart } from "lucide-react"
import Link from "next/link"

export default function AgentsPage() {
  const agents = [
    { id: "elara", name: "Elara", role: "Orchestrator", desc: "The central intelligence that coordinates all other agents and manages complex workflows.", icon: Brain },
    { id: "sankofa", name: "Sankofa", role: "Knowledge Specialist", desc: "Expert in historical context, documentation, and retrieving insights from the Knowledge Ocean.", icon: Search },
    { id: "themba", name: "Themba", role: "Security Auditor", desc: "Ensures all code and actions comply with the Azora Constitution and security best practices.", icon: Shield },
    { id: "jabari", name: "Jabari", role: "Performance Engineer", desc: "Optimizes code for speed, efficiency, and scalability across distributed systems.", icon: Zap },
    { id: "nia", name: "Nia", role: "Product Strategist", desc: "Translates high-level vision into actionable technical specifications and roadmaps.", icon: BarChart },
    { id: "imani", name: "Imani", role: "UI/UX Specialist", desc: "Crafts beautiful, accessible, and responsive user interfaces from design concepts.", icon: Palette },
    { id: "kwame", name: "Kwame", role: "Backend Architect", desc: "Designs robust database schemas, API architectures, and server-side logic.", icon: Code },
    { id: "zola", name: "Zola", role: "Communication Lead", desc: "Manages team collaboration, notifications, and external integrations like Slack.", icon: MessageSquare }
  ];

  return (
    <div className="min-h-screen bg-[#0d1117] text-white">
      <Navbar />
      <main className="py-24 px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-7xl">
          <div className="text-center mb-20">
            <h1 className="text-5xl md:text-7xl font-bold mb-6 bg-gradient-to-r from-emerald-400 to-blue-500 bg-clip-text text-transparent">
              Meet the AI Family
            </h1>
            <p className="text-xl text-gray-400 max-w-3xl mx-auto">
              A team of specialized agents working in harmony to transform 
              your ideas into production-ready reality.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-24">
            {agents.map((agent) => (
              <div key={agent.id} className="group p-8 rounded-2xl bg-white/5 border border-white/10 hover:border-emerald-400/30 transition-all flex flex-col items-center text-center">
                <div className="mb-6 relative">
                  <AfricanAgentAvatar agent={agent.id as any} size="lg" showAura showGlow />
                </div>
                <h3 className="text-2xl font-bold mb-1 group-hover:text-emerald-400 transition-colors">{agent.name}</h3>
                <span className="text-xs font-bold uppercase tracking-widest text-emerald-400/60 mb-4">{agent.role}</span>
                <p className="text-gray-400 text-sm leading-relaxed">{agent.desc}</p>
              </div>
            ))}
          </div>

          <div className="p-12 rounded-3xl bg-gradient-to-br from-emerald-500/10 to-blue-500/10 border border-white/10">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <div>
                <h2 className="text-4xl font-bold mb-6">Collective Intelligence</h2>
                <p className="text-gray-400 leading-relaxed mb-8">
                  Unlike generic AI assistants, Azora agents are specialized. 
                  They communicate with each other, share context, and validate 
                  each other's work to ensure the highest quality output.
                </p>
                <div className="grid grid-cols-2 gap-4">
                  <div className="p-4 rounded-xl bg-black/40 border border-white/5">
                    <h4 className="font-bold text-emerald-400 mb-1">Context Sharing</h4>
                    <p className="text-xs text-gray-500">Agents maintain a shared memory of your project goals.</p>
                  </div>
                  <div className="p-4 rounded-xl bg-black/40 border border-white/5">
                    <h4 className="font-bold text-emerald-400 mb-1">Cross-Validation</h4>
                    <p className="text-xs text-gray-500">Security agents audit code generated by development agents.</p>
                  </div>
                </div>
              </div>
              <div className="relative aspect-square rounded-2xl overflow-hidden border border-white/10 bg-black/40 flex items-center justify-center">
                <div className="absolute inset-0 opacity-20 bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-emerald-500 via-transparent to-transparent" />
                <div className="relative z-10 text-center">
                  <Brain className="h-24 w-24 text-emerald-400 mx-auto mb-4 animate-pulse" />
                  <p className="text-gray-400 font-mono text-sm">Orchestration Engine Online</p>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-20 text-center">
            <Link href="/features" className="text-emerald-400 hover:underline">Explore Platform Features</Link>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
