[Interface]
PrivateKey = OF2dVzNJaDhQXLOcT8CRcwnE6hY+SCTGKEQOsFFhl38=
Address = 10.0.0.1/24
ListenPort = 51820

# IP Forwarding and NAT
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# These are the Peers (Clients) that can join the Aethernet

# [Peer] - Your Phone
# [Peer]
# PublicKey = <Phone_Public_Key>
# AllowedIPs = 10.0.0.2/32

# [Peer] - Your Vivobook
# [Peer]
# PublicKey = <Vivobook_Public_Key>
# AllowedIPs = 10.0.0.3/32