import { Navbar } from "@/components/features/navbar"
import { Footer } from "@/components/features/footer"
import { FileText } from "lucide-react"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0d1117] text-white">
      <Navbar />
      <main>
        <section className="relative py-24 lg:py-32 px-4 sm:px-6 lg:px-8 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-b from-gray-500/5 to-transparent" />
          <div className="relative mx-auto max-w-4xl text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-gray-500/10 border border-gray-500/20 text-gray-400 text-xs font-bold uppercase tracking-wider mb-6">
              <FileText className="h-3.5 w-3.5" />
              Terms of Service
            </div>
            <h1 className="text-4xl sm:text-5xl font-bold mb-6">
              Terms of
              <span className="bg-gradient-to-r from-gray-400 to-gray-300 bg-clip-text text-transparent"> Service</span>
            </h1>
            <p className="text-sm text-gray-500">Last updated: January 15, 2026</p>
          </div>
        </section>

        <section className="py-12 px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-3xl">
            <div className="space-y-8">
              {[
                { title: "1. Acceptance of Terms", content: "By accessing or using Azora BuildSpaces, you agree to be bound by these Terms of Service. If you do not agree, do not use the service." },
                { title: "2. Description of Service", content: "BuildSpaces is a cloud-based integrated development environment with AI-powered agents, real-time collaboration, and workspace management tools." },
                { title: "3. User Accounts", content: "You must provide accurate information when creating an account. You are responsible for maintaining the security of your account credentials. You must be at least 16 years old to use the service." },
                { title: "4. Acceptable Use", content: "You may not use BuildSpaces to: generate malicious software, violate any laws, infringe on intellectual property rights, attempt to circumvent Constitutional AI safety measures, or abuse AI agents." },
                { title: "5. Your Content", content: "You retain full ownership of all code, specifications, and content you create using BuildSpaces. We claim no intellectual property rights over your work." },
                { title: "6. AI Agent Usage", content: "AI agents provide suggestions and assistance only. You are responsible for reviewing and accepting any AI-generated code or content. All agent actions are subject to Constitutional AI validation." },
                { title: "7. Open Source License", content: "The BuildSpaces platform is open source under the MIT License. Self-hosted instances are governed by the MIT License terms. The hosted service (azora.dev) is additionally governed by these Terms." },
                { title: "8. Payment Terms", content: "Paid plans are billed monthly or annually. You may cancel at any time. Refunds are provided pro-rata for annual plans. No refunds for monthly plans." },
                { title: "9. Limitation of Liability", content: "BuildSpaces is provided \"as is\" without warranties. We are not liable for any damages arising from the use of AI suggestions, code generated by agents, or service interruptions." },
                { title: "10. Changes to Terms", content: "We may modify these terms with 30 days notice. Continued use after changes constitutes acceptance." },
              ].map((section, i) => (
                <div key={i} className="p-6 rounded-xl bg-white/[0.02] border border-white/[0.06]">
                  <h2 className="text-lg font-semibold mb-3">{section.title}</h2>
                  <p className="text-sm text-gray-400 leading-relaxed">{section.content}</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  )
}
